# Generated by Django 5.2.5 on 2025-08-18 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('link', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'db_table': 'publishers',
                'ordering': ['-created_at', 'id'],
                'default_related_name': 'publishers',
                'indexes': [models.Index(fields=['created_at'], name='publishers_created_a3a360_idx'), models.Index(fields=['name'], name='publishers_name_24248c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('link', models.URLField(max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.publisher')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'db_table': 'publications',
                'ordering': ['-published_at', 'id'],
                'default_related_name': 'publications',
                'indexes': [models.Index(fields=['published_at'], name='publication_publish_be13ef_idx'), models.Index(fields=['title'], name='publication_title_2b1218_idx')],
            },
        ),
    ]
