# Generated by Django 5.2.5 on 2025-08-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='link',
            new_name='website',
        ),
    ]
