# Generated by Django 5.2.5 on 2025-08-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_rename_link_publisher_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(max_length=5000),
        ),
    ]
