# Generated by Django 5.2.5 on 2025-08-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_publisher_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.URLField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
