# Generated by Django 5.2.5 on 2025-08-19 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_alter_publication_link_alter_publication_title'),
        ('stories', '0002_auto_20250101_0001'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sources',
            field=models.ManyToManyField(blank=True, to='sources.publication'),
        ),
        migrations.AlterField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['is_current'], name='stories_is_curr_f4d19a_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user', 'is_current'], name='stories_user_id_273a79_idx'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user', 'is_current'), name='unique_current_story_per_user'),
        ),
    ]
